apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: redis-pod
  name: redis-pod
spec:
  containers:
    - image: redis:7.0
      name: redis-pod
      ports:
        - containerPort: 6379
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
