# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx-app
  ports:
    - port: 80
      targetPort: 80  # Changed from 8080 to 80
      nodePort: 30080
  type: NodePort