apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-app-replicaset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx-app
          image: nginx:alpine
          ports:
            - containerPort: 8080
